package qdvc.checklists.android.app.data.index

import androidx.room.ColumnInfo
import androidx.room.Dao
import androidx.room.Database
import androidx.room.Entity
import androidx.room.Fts4
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.PrimaryKey
import androidx.room.Query
import androidx.room.RoomDatabase

/**
 * One row per checklist. Keyed by an autogenerated Long [rowId] — kept exactly
 * as-is so Room maps it to SQLite's true rowid, which the FTS content linkage
 * requires (B10). Unique on (workspaceUri, docId).
 */
@Entity(
    tableName = "checklists",
    indices = [androidx.room.Index(value = ["workspaceUri", "docId"], unique = true)]
)
data class ChecklistEntity(
    @PrimaryKey(autoGenerate = true) val rowId: Long = 0,
    val workspaceUri: String,
    val docId: String,
    val cid: String,
    val title: String,
    val lastModified: Long,
    @ColumnInfo(name = "content") val content: String,
)

/** FTS4 shadow over the `content` column. Room generates the sync triggers. */
@Fts4(contentEntity = ChecklistEntity::class)
@Entity(tableName = "checklists_fts")
data class ChecklistFts(
    @ColumnInfo(name = "content") val content: String,
)

/** Per-workspace index metadata for the status surface. */
@Entity(tableName = "index_meta")
data class IndexMeta(
    @PrimaryKey val workspaceUri: String,
    val lastRegenerated: Long,
    val count: Int,
)

data class SearchHit(
    val workspaceUri: String,
    val docId: String,
    val cid: String,
    val title: String,
    val snippet: String,
)

@Dao
interface IndexDao {

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun upsert(entity: ChecklistEntity)

    @Query("DELETE FROM checklists WHERE workspaceUri = :ws")
    fun clearWorkspace(ws: String)

    @Query("DELETE FROM checklists WHERE workspaceUri = :ws AND docId = :docId")
    fun deleteOne(ws: String, docId: String)

    @Query("SELECT docId, lastModified FROM checklists WHERE workspaceUri = :ws")
    fun fingerprints(ws: String): List<Fingerprint>

    @Query(
        "SELECT workspaceUri, docId, cid, title FROM checklists " +
            "WHERE workspaceUri = :ws ORDER BY title COLLATE NOCASE"
    )
    fun listAll(ws: String): List<ListRow>

    @Query("SELECT COUNT(*) FROM checklists WHERE workspaceUri = :ws")
    fun countFor(ws: String): Int

    /** Body matches via FTS, plus title LIKE matches (FTS indexes bodies only). */
    @Query(
        "SELECT c.workspaceUri AS workspaceUri, c.docId AS docId, c.cid AS cid, " +
            "c.title AS title, snippet(checklists_fts) AS snippet " +
            "FROM checklists_fts JOIN checklists AS c ON c.rowId = checklists_fts.rowid " +
            "WHERE c.workspaceUri = :ws AND checklists_fts MATCH :match"
    )
    fun searchBodies(ws: String, match: String): List<SearchHit>

    @Query(
        "SELECT workspaceUri, docId, cid, title, '' AS snippet FROM checklists " +
            "WHERE workspaceUri = :ws AND title LIKE :like COLLATE NOCASE"
    )
    fun searchTitles(ws: String, like: String): List<SearchHit>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun setMeta(meta: IndexMeta)

    @Query("SELECT * FROM index_meta WHERE workspaceUri = :ws")
    fun meta(ws: String): IndexMeta?
}

data class Fingerprint(val docId: String, val lastModified: Long)
data class ListRow(val workspaceUri: String, val docId: String, val cid: String, val title: String)

@Database(
    entities = [ChecklistEntity::class, ChecklistFts::class, IndexMeta::class],
    version = 1,
    exportSchema = false,
)
abstract class IndexDatabase : RoomDatabase() {
    abstract fun dao(): IndexDao
}
