package qdvc.checklists.android.app.data.index

import androidx.room.ColumnInfo
import androidx.room.Dao
import androidx.room.Database
import androidx.room.Entity
import androidx.room.Fts4
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.PrimaryKey
import androidx.room.Query
import androidx.room.RoomDatabase
import androidx.room.Transaction
import kotlinx.coroutines.flow.Flow

/**
 * The on-device read model for every workspace.
 *
 * The workspace folders remain the system of record: this database is a
 * *projection* of them, rebuilt by a full scan whenever the app launches (see
 * `WorkspaceStore.ingest`). Every create/update/delete is written straight
 * through to the filesystem as it happens, so the database never holds state
 * that exists nowhere else — which is what keeps `fallbackToDestructiveMigration`
 * a safe choice and lets a corrupt database be thrown away without data loss.
 *
 * The UI reads only from here, via [Flow] queries, so navigating between
 * checklists and ticking items never touches the Storage Access Framework.
 */

/**
 * One row per checklist. Keyed by an autogenerated Long [rowId] — kept exactly
 * as-is so Room maps it to SQLite's true rowid, which the FTS content linkage
 * requires (B10). Unique on (workspaceUri, docId).
 */
@Entity(
    tableName = "checklists",
    indices = [androidx.room.Index(value = ["workspaceUri", "docId"], unique = true)]
)
data class ChecklistEntity(
    @PrimaryKey(autoGenerate = true) val rowId: Long = 0,
    val workspaceUri: String,
    val docId: String,
    val cid: String,
    val title: String,
    val description: String,
    /** On-disk folder name, e.g. "BCL091-resupply-lunar-base". The log's key. */
    val folderName: String,
    val lastModified: Long,
    /** Title + description + every node's text, for full-text search. */
    @ColumnInfo(name = "content") val content: String,
)

/** FTS4 shadow over the `content` column. Room generates the sync triggers. */
@Fts4(contentEntity = ChecklistEntity::class)
@Entity(tableName = "checklists_fts")
data class ChecklistFts(
    @ColumnInfo(name = "content") val content: String,
)

/**
 * One row per heading/item. [seqGroup]/[seqNumber]/[sortName] are the persisted
 * form of `Naming.nodeSortKey`, so ordering happens in SQL rather than in Kotlin:
 * folders with an `NN-` prefix first (by number), then the rest by folder name.
 */
@Entity(
    tableName = "nodes",
    primaryKeys = ["workspaceUri", "docId"],
    indices = [androidx.room.Index(value = ["workspaceUri", "checklistDocId"])]
)
data class NodeEntity(
    val workspaceUri: String,
    val docId: String,
    val checklistDocId: String,
    /** Denormalised so done-state and log rows can join on folder names alone. */
    val checklistFolder: String,
    val folderName: String,
    val title: String,
    val description: String,
    /** `NodeKind.wire` — "heading" or "item". */
    val kind: String,
    val seqGroup: Int,
    val seqNumber: Int,
    val sortName: String,
)

/**
 * Current completion state, derived by replaying the daily logs at ingest and
 * kept up to date as marks are made. Keyed by the same workspace-relative folder
 * names the logs use, never by SAF document ids.
 */
@Entity(
    tableName = "done_state",
    primaryKeys = ["workspaceUri", "checklistFolder", "itemFolder"]
)
data class DoneStateEntity(
    val workspaceUri: String,
    val checklistFolder: String,
    val itemFolder: String,
    val done: Boolean,
    val markedAt: String?,
)

/** Every row from every daily log, so item history is an indexed query. */
@Entity(
    tableName = "log_entries",
    indices = [
        androidx.room.Index(value = ["workspaceUri", "checklistFolder", "itemFolder"]),
    ]
)
data class LogEntryEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val workspaceUri: String,
    val timestamp: String,
    val action: String,
    val client: String,
    val checklistFolder: String,
    val itemFolder: String,
)

/** Per-workspace projection metadata for the status surface. */
@Entity(tableName = "index_meta")
data class IndexMeta(
    @PrimaryKey val workspaceUri: String,
    val lastRegenerated: Long,
    val count: Int,
)

// --- projections ---------------------------------------------------------- //

data class SearchHit(
    val workspaceUri: String,
    val docId: String,
    val cid: String,
    val title: String,
    val snippet: String,
)

/** A node plus its resolved done-state; `done` is null when never marked. */
data class NodeWithState(
    val docId: String,
    val folderName: String,
    val title: String,
    val description: String,
    val kind: String,
    val done: Boolean?,
    val markedAt: String?,
)

/** One logged action, most-recent-first, for the Info tab's history list. */
data class LogLine(val timestamp: String, val action: String)

@Dao
abstract class IndexDao {

    // --- ingest (full rebuild of one workspace) --------------------------- //

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    abstract suspend fun insertChecklist(entity: ChecklistEntity): Long

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    abstract suspend fun insertNodes(rows: List<NodeEntity>)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    abstract suspend fun insertDoneStates(rows: List<DoneStateEntity>)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    abstract suspend fun insertLogEntries(rows: List<LogEntryEntity>)

    @Query("DELETE FROM checklists WHERE workspaceUri = :ws")
    abstract suspend fun deleteChecklists(ws: String)

    @Query("DELETE FROM nodes WHERE workspaceUri = :ws")
    abstract suspend fun deleteNodes(ws: String)

    @Query("DELETE FROM done_state WHERE workspaceUri = :ws")
    abstract suspend fun deleteDoneStates(ws: String)

    @Query("DELETE FROM log_entries WHERE workspaceUri = :ws")
    abstract suspend fun deleteLogEntries(ws: String)

    /** Drop everything belonging to one workspace, ready for a fresh ingest. */
    @Transaction
    open suspend fun clearWorkspace(ws: String) {
        deleteChecklists(ws)
        deleteNodes(ws)
        deleteDoneStates(ws)
        deleteLogEntries(ws)
    }

    // --- single-checklist refresh (after a structural write) -------------- //

    @Query("DELETE FROM checklists WHERE workspaceUri = :ws AND docId = :docId")
    abstract suspend fun deleteChecklist(ws: String, docId: String)

    @Query("DELETE FROM nodes WHERE workspaceUri = :ws AND checklistDocId = :checklistDocId")
    abstract suspend fun deleteNodesOf(ws: String, checklistDocId: String)

    /** Replace one checklist's row and all of its nodes, atomically. */
    @Transaction
    open suspend fun replaceChecklist(
        ws: String,
        docId: String,
        checklist: ChecklistEntity,
        nodes: List<NodeEntity>,
    ) {
        deleteChecklist(ws, docId)
        deleteNodesOf(ws, docId)
        insertChecklist(checklist)
        insertNodes(nodes)
    }

    // --- observation (the UI's only read path) ---------------------------- //

    @Query("SELECT * FROM checklists WHERE workspaceUri = :ws ORDER BY folderName")
    abstract fun observeChecklists(ws: String): Flow<List<ChecklistEntity>>

    @Query("SELECT * FROM nodes WHERE workspaceUri = :ws")
    abstract fun observeAllNodes(ws: String): Flow<List<NodeEntity>>

    @Query("SELECT * FROM checklists WHERE workspaceUri = :ws AND docId = :docId LIMIT 1")
    abstract fun observeChecklist(ws: String, docId: String): Flow<ChecklistEntity?>

    @Query(
        "SELECT n.docId AS docId, n.folderName AS folderName, n.title AS title, " +
            "n.description AS description, n.kind AS kind, " +
            "d.done AS done, d.markedAt AS markedAt " +
            "FROM nodes AS n " +
            "LEFT JOIN done_state AS d ON d.workspaceUri = n.workspaceUri " +
            "AND d.checklistFolder = n.checklistFolder AND d.itemFolder = n.folderName " +
            "WHERE n.workspaceUri = :ws AND n.checklistDocId = :checklistDocId " +
            "ORDER BY n.seqGroup, n.seqNumber, n.sortName"
    )
    abstract fun observeNodes(ws: String, checklistDocId: String): Flow<List<NodeWithState>>

    @Query(
        "SELECT timestamp, action FROM log_entries " +
            "WHERE workspaceUri = :ws AND checklistFolder = :checklistFolder " +
            "AND itemFolder = :itemFolder ORDER BY timestamp DESC"
    )
    abstract fun observeItemLog(
        ws: String,
        checklistFolder: String,
        itemFolder: String,
    ): Flow<List<LogLine>>

    // --- mark / unmark ---------------------------------------------------- //

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    abstract suspend fun upsertDoneStates(rows: List<DoneStateEntity>)

    @Query(
        "SELECT * FROM done_state WHERE workspaceUri = :ws " +
            "AND checklistFolder = :checklistFolder AND itemFolder = :itemFolder LIMIT 1"
    )
    abstract suspend fun doneStateFor(
        ws: String,
        checklistFolder: String,
        itemFolder: String,
    ): DoneStateEntity?

    @Query(
        "SELECT * FROM done_state WHERE workspaceUri = :ws AND checklistFolder = :checklistFolder"
    )
    abstract suspend fun doneStatesFor(ws: String, checklistFolder: String): List<DoneStateEntity>

    @Query(
        "DELETE FROM done_state WHERE workspaceUri = :ws " +
            "AND checklistFolder = :checklistFolder AND itemFolder = :itemFolder"
    )
    abstract suspend fun deleteDoneState(ws: String, checklistFolder: String, itemFolder: String)

    @Query(
        "DELETE FROM log_entries WHERE workspaceUri = :ws AND timestamp = :timestamp " +
            "AND checklistFolder = :checklistFolder AND itemFolder IN (:itemFolders)"
    )
    abstract suspend fun deleteLogEntriesAt(
        ws: String,
        timestamp: String,
        checklistFolder: String,
        itemFolders: List<String>,
    )

    // --- rename fix-ups (mirroring what the on-disk rewrite did) ---------- //

    @Query(
        "UPDATE done_state SET checklistFolder = :new " +
            "WHERE workspaceUri = :ws AND checklistFolder = :old"
    )
    abstract suspend fun renameChecklistInDoneState(ws: String, old: String, new: String)

    @Query(
        "UPDATE log_entries SET checklistFolder = :new " +
            "WHERE workspaceUri = :ws AND checklistFolder = :old"
    )
    abstract suspend fun renameChecklistInLog(ws: String, old: String, new: String)

    @Query(
        "UPDATE nodes SET checklistFolder = :new " +
            "WHERE workspaceUri = :ws AND checklistFolder = :old"
    )
    abstract suspend fun renameChecklistInNodes(ws: String, old: String, new: String)

    @Query(
        "UPDATE done_state SET itemFolder = :new WHERE workspaceUri = :ws " +
            "AND checklistFolder = :checklistFolder AND itemFolder = :old"
    )
    abstract suspend fun renameNodeInDoneState(
        ws: String,
        checklistFolder: String,
        old: String,
        new: String,
    )

    @Query(
        "UPDATE log_entries SET itemFolder = :new WHERE workspaceUri = :ws " +
            "AND checklistFolder = :checklistFolder AND itemFolder = :old"
    )
    abstract suspend fun renameNodeInLog(
        ws: String,
        checklistFolder: String,
        old: String,
        new: String,
    )

    // --- status & search --------------------------------------------------- //

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    abstract suspend fun setMeta(meta: IndexMeta)

    @Query("SELECT * FROM index_meta WHERE workspaceUri = :ws")
    abstract suspend fun meta(ws: String): IndexMeta?

    @Query("DELETE FROM index_meta WHERE workspaceUri = :ws")
    abstract suspend fun deleteMeta(ws: String)

    /** Body matches via FTS, plus title LIKE matches (FTS indexes bodies only). */
    @Query(
        "SELECT c.workspaceUri AS workspaceUri, c.docId AS docId, c.cid AS cid, " +
            "c.title AS title, snippet(checklists_fts) AS snippet " +
            "FROM checklists_fts JOIN checklists AS c ON c.rowId = checklists_fts.rowid " +
            "WHERE c.workspaceUri = :ws AND checklists_fts MATCH :match"
    )
    abstract suspend fun searchBodies(ws: String, match: String): List<SearchHit>

    @Query(
        "SELECT workspaceUri, docId, cid, title, '' AS snippet FROM checklists " +
            "WHERE workspaceUri = :ws AND title LIKE :like COLLATE NOCASE"
    )
    abstract suspend fun searchTitles(ws: String, like: String): List<SearchHit>
}

@Database(
    entities = [
        ChecklistEntity::class,
        ChecklistFts::class,
        NodeEntity::class,
        DoneStateEntity::class,
        LogEntryEntity::class,
        IndexMeta::class,
    ],
    version = 2,
    exportSchema = false,
)
abstract class IndexDatabase : RoomDatabase() {
    abstract fun dao(): IndexDao
}
